version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./postgres/database.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080